# -*- coding: utf-8 -*-
"""26_02_2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxVCLj6R_xBsnxih_IFeqsPwOUhHUjQO
"""

from collections import Counter

text = ('this is sample text with several words '
'this is more sample text with some different words')

counter = Counter(text.split())

for word, count in sorted(counter.items()):
  print(f'{word:<12} {count}')

country_codes ={}

country_codes.update({'South Africa': 'za'})

country_codes

country_codes.update(Australia = "ar")

country_codes

country_codes.update(Australia = "au")

country_codes

months1 = {'January': 1, 'February': 2, 'March':3}

months2 = {number: name for name, number in months1.items()}

months2

months1 = {'January': 1, 'February': 2, 'March':2}

months2 = {number: name for name, number in months1.items()}

months2

grades = {'Sue': [98, 87, 94], 'Bob': [84, 95, 91]}

grades2 = {k: sum(v) / len(v) for k, v in grades.items()}

grades2

colors = {'red', 'orange', 'yellow', 'green', 'red', 'blue'}

colors

len(colors)

for color in colors:
  print(color.upper())

numbers = list(range(10)) + list(range(5))

numbers

set(numbers)

{1,3,5} | {2,3,4}

{1,3,5}.union({2,3,4})

{1,3,5}.union([20, 20,3,40, 40])

{1,3,5} & {2,3,4}

{1,3,5}.intersection([1,2,2,3,3,4,4])

{1,3,5} - {2,3,4}

{1,3,5,7}.difference([2,2,3,3,4,4])

{1,3,5} ^ {2,3,4}

{1,3,5,7}.symmetric_difference([2,2,3,3,4,4])

{1,3,5}.isdisjoint({2,3,4})

{1,3,5}.isdisjoint({2,4,6})

numbers = {1,3,5}
numbers |= {2,3,4}
numbers

numbers.update(range(10))
numbers

numbers.add(17)
numbers.add(3)
numbers

numbers.remove(3)
numbers

numbers.discard(3)
numbers

numbers.pop()

numbers

numbers.clear()

numbers

numbers = [1,2,2,3,4,5,6,6,7,8,9,10,10]

evens = {i for i in numbers if i % 2 ==0}

evens

